---
- block:
  - name: setup dehydrated domain name list
    lineinfile:
      path: "/etc/dehydrated/domains.txt"
      line: "{{ item }}"
      create: "yes"
    loop: "{{ letsencrypt_auth_domain_names }}"

  - name: check if cert file exists
    stat:
      path: "/var/lib/dehydrated/certs/{{ item }}/fullchain.pem"
    loop: "{{ letsencrypt_auth_domain_names }}"
    register: "certs_file"

  - name: install nginx config
    template:
      src: "nginx_before_auth.j2"
      dest: "/etc/nginx/sites-available/{{ item.0 }}"
      owner: "root"
      group: "root"
      mode: "0644"
    when: "not item.1.stat.exists"
    loop: "{{ letsencrypt_auth_domain_names|zip(certs_file.results)|list }}"

  - name: create soft link
    file:
      src: "/etc/nginx/sites-available/{{ item.0 }}"
      dest: "/etc/nginx/sites-enabled/{{ item.0 }}"
      owner: "root"
      group: "root"
      state: "link"
    when: "not item.1.stat.exists"
    loop: "{{ letsencrypt_auth_domain_names|zip(certs_file.results)|list }}"

  - name: reload nginx
    systemd: state=reloaded name=nginx

  - name: getting certs
    command: "/usr/local/sbin/dehydrated-0.6.5 -c"

  - name: check if nginx conf already has ssl settings
    find:
      path: "/etc/nginx/sites-available/"
      pattern: "{{ item }}"
      contains: "^\s*ssl\s*on\s*;"
    register: "nginx_config_ssl_enabled"
    loop: "{{ letsencrypt_auth_domain_names }}"

  - name: activate certs
    template:
      src: "nginx_after_auth.j2"
      dest: "/etc/nginx/sites-available/{{ item.0 }}"
      owner: "root"
      group: "root"
      mode: "0644"
    when: not item.1.matched
    loop: "{{ letsencrypt_auth_domain_names|zip(nginx_config_ssl_enabled.results)|list }}"

  - name: "reload nginx"
    systemd: "state=reloaded name=nginx"
  tags:
    - letsencrypt_auth
